### ISSUE TITLE
Calling C example + printf wrapper

### ISSUE THREAD

**Issue by arabine** [Robert-van-Engelen/lisp#3]
Hello,

What a wonderful lisp implementation, good job. Can you please add at least one example of how to call a new C defined function from lisp? (I am new to Lisp so maybe I missed it in the readme).

As it is a good candidate for many embedded platforms (microcontrollers), maybe it could be worth to wrap the (f)printf functions so that theses ones are defined on the host side rather than in the library.

Thank you!

**Comment by Robert-van-Engelen** [comment]
Thank you for your feedback. To call a C function it may be easiest to define it as a primitive at compile time. A primitive takes a list of arguments of type `L` (Lisp) and an environment of type `L*`. It  returns a value of type `L`. For example, to traverse the list of arguments looks like this:

    f_func(L t, L *e) {
      L s;
      for (s = t; T(s) != NIL; s = cdr(s)) {
          ... car(s) ...; // value of argument
      }
      return ... value of type L ...;
    }

Then add an entry to the `prim[]` array as a `NORMAL` function:

    {"c_func",     f_func,    NORMAL},

It is possible to add functionality to the Lisp implementation to dynamically call a C function, but I haven't looked into that yet.

**Comment by arabine** [comment]
Ok perfect. Extending the implementation at build time is enough I think.

Regarding the printf stuff, do you believe it would be possible to call a macro or any other solution? Maybe calling a user defined printf function following your last reply?

I'm imaging for instance moving this:

`L f_print(L t, L *_) {
  for (; T(t) != NIL; t = cdr(t))
    print(car(t));
  return nil;
}
`
out of the library, on the user side. For embedded platforms, we usually do not need any print information except for debugging.

Regards!
Anthony

**Comment by Robert-van-Engelen** [comment]
The `prim[]` table is in principle extensible. Perhaps moving this table out of the lisp.c source into a separate file is better, then also have a lisp.h file with declarations etc. And instead of a static `prim[]` table we could allocate it dynamically and have a simple API to add definitions to the table. This allows external code to add definitions, which should be done before Lisp is initialized. Is that what you are looking for?

Dynamically calling a C function by name would be nice and can be hacked with Linux ELF using `<elf.h>` and `<libelf.h>`. It's not portable and not something I can recommend.

**Comment by Robert-van-Engelen** [comment]
I've updated the README to explain how to embed the Lisp interpreter and register C functions. See the bottom of the README. Is this helpful? Should I add more?

**Comment by arabine** [comment]
Hi,
Sorry for the delay. A solution witout modifying the interpreter files would be the best, indeed!

I saw a simple implementation in this Forth interpreter: https://github.com/zevv/zForth/blob/master/src/linux/main.c

It is possible to call a host/user function, and using a simple ID to access to various functions.

Thanks for the documentation update, this is clear enough.
