### ISSUE TITLE
Wrong read() silently linked when using readline

### ISSUE THREAD

**Issue by ndrory** [Robert-van-Engelen/lisp#5]
I’ve encountered a problem leading to infinite recursion because the wrong ‘int read()’ function is being linked (silently) when using readline. I’ve verified this happens on two distinct systems (Redhat Linux, Alpine Linux). The solution is to rename the read() symbol in lisp.c to lread() or anything other than read().

**Comment by Robert-van-Engelen** [comment]
We should rename it then. Perhaps `expr()` since it returns a parsed Lisp expression.

It's a really annoying side effect of using `readline` I suppose.

Thanks for reporting!

**Comment by Robert-van-Engelen** [comment]
Or perhaps `lread()` as you suggest or `readl()`. It is nicer to continue using the `read` name, since our REPL is this short nice line: `print(eval(*push(readl()), env))`.

**Comment by Robert-van-Engelen** [comment]
I've also updated the [tinylisp](https://github.com/Robert-van-Engelen/tinylisp) and [lisp-cheney](https://github.com/Robert-van-Engelen/lisp-cheney) projects to avoid this potential issue.
